services:
  app:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:8.4.4
    # Configure to use Redis as a durable persistence service
    # Without those, it behaves as an ephemeral cache
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--appendfsync",
        "always",
        "--maxmemory-policy",
        "noeviction",
      ]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  redis-data:
